//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDotNet.Graphics.Internals {
	
	
	internal partial class DelegateNativeMethods {
		
		[System.Runtime.InteropServices.UnmanagedFunctionPointerAttribute(System.Runtime.InteropServices.CallingConvention.Cdecl)]
		delegate void _R_GE_checkVersionOrDie(int version);
		
		public void R_GE_checkVersionOrDie(int version) {
			var function = this.dll.GetFunction<_R_GE_checkVersionOrDie>("R_GE_checkVersionOrDie");
			function(  version);
		}
		
		[System.Runtime.InteropServices.UnmanagedFunctionPointerAttribute(System.Runtime.InteropServices.CallingConvention.Cdecl)]
		delegate void _R_CheckDeviceAvailable();
		
		public void R_CheckDeviceAvailable() {
			var function = this.dll.GetFunction<_R_CheckDeviceAvailable>("R_CheckDeviceAvailable");
			function();
		}
		
		[System.Runtime.InteropServices.UnmanagedFunctionPointerAttribute(System.Runtime.InteropServices.CallingConvention.Cdecl)]
		delegate void _Rf_onintr();
		
		public void Rf_onintr() {
			var function = this.dll.GetFunction<_Rf_onintr>("Rf_onintr");
			function();
		}
		
		[System.Runtime.InteropServices.UnmanagedFunctionPointerAttribute(System.Runtime.InteropServices.CallingConvention.Cdecl)]
		delegate System.IntPtr _GEcreateDevDesc(System.IntPtr dev);
		
		public System.IntPtr GEcreateDevDesc(System.IntPtr dev) {
			var function = this.dll.GetFunction<_GEcreateDevDesc>("GEcreateDevDesc");
			return function(  dev);
		}
		
		[System.Runtime.InteropServices.UnmanagedFunctionPointerAttribute(System.Runtime.InteropServices.CallingConvention.Cdecl)]
		delegate void _GEaddDevice2(System.IntPtr dev, [System.Runtime.InteropServices.MarshalAsAttribute(System.Runtime.InteropServices.UnmanagedType.LPStr)] string name);
		
		public void GEaddDevice2(System.IntPtr dev, string name) {
			var function = this.dll.GetFunction<_GEaddDevice2>("GEaddDevice2");
			function(  dev,   name);
		}
	}
}
