//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDotNet.Graphics.Internals {
	
	
	internal partial class DirectNativeMethods {
		
[System.Runtime.InteropServices.DllImportAttribute(Constants.RDllName, CallingConvention = System.Runtime.InteropServices.CallingConvention.Cdecl, EntryPoint = "R_GE_checkVersionOrDie")]
private static extern void _R_GE_checkVersionOrDie(System.Int32 version);
		
		public void R_GE_checkVersionOrDie(int version) {
			DirectNativeMethods._R_GE_checkVersionOrDie(  version);
		}
		
[System.Runtime.InteropServices.DllImportAttribute(Constants.RDllName, CallingConvention = System.Runtime.InteropServices.CallingConvention.Cdecl, EntryPoint = "R_CheckDeviceAvailable")]
private static extern void _R_CheckDeviceAvailable();
		
		public void R_CheckDeviceAvailable() {
			DirectNativeMethods._R_CheckDeviceAvailable();
		}
		
[System.Runtime.InteropServices.DllImportAttribute(Constants.RDllName, CallingConvention = System.Runtime.InteropServices.CallingConvention.Cdecl, EntryPoint = "Rf_onintr")]
private static extern void _Rf_onintr();
		
		public void Rf_onintr() {
			DirectNativeMethods._Rf_onintr();
		}
		
[System.Runtime.InteropServices.DllImportAttribute(Constants.RDllName, CallingConvention = System.Runtime.InteropServices.CallingConvention.Cdecl, EntryPoint = "GEcreateDevDesc")]
private static extern System.IntPtr _GEcreateDevDesc(System.IntPtr dev);
		
		public System.IntPtr GEcreateDevDesc(System.IntPtr dev) {
			return DirectNativeMethods._GEcreateDevDesc(  dev);
		}
		
[System.Runtime.InteropServices.DllImportAttribute(Constants.RDllName, CallingConvention = System.Runtime.InteropServices.CallingConvention.Cdecl, EntryPoint = "GEaddDevice2")]
private static extern void _GEaddDevice2(System.IntPtr dev, [System.Runtime.InteropServices.MarshalAsAttribute(System.Runtime.InteropServices.UnmanagedType.LPStr)] System.String name);
		
		public void GEaddDevice2(System.IntPtr dev, string name) {
			DirectNativeMethods._GEaddDevice2(  dev,   name);
		}
	}
}
